CLOUD-845 Added a doc how to troubleshoot Operator installation
percona/k8spg-docs pull request #191
Opened 2024-06-05 17:07 UTC by nastena1606

2025-03-28 09:29 UTC, fiowro commented
The doc is good, but I think it needs a little bit different name. Here we are troubleshooting the Kubernetes cluster (or Kubernetes environment, you may say). The "installation" word is used in our TOC to point at the installation process, not the environment.

Also, putting this to the 1st place in the troubleshooting subsection in TOC is questionable. First we have this doc, and *then* we have initial troubleshooting. I'd recommend naming this as "Kubernetes troubleshooting" and putting it to the very end of the subsection. Reasons for such a placement: It's a supplementary doc, it is not about our Operator; also, env troubleshooting is a rare thing to do, compared with our other troubleshooting docs.

2025-11-12 05:35 UTC, egegunes requested changes

2025-11-12 05:35 UTC, egegunes commented on docs/troubleshoot-operator.md
> +    The cluster should typically be in the `Running` state. It may briefly enter the `initializing` state while reconciling changes. If the cluster remains in the `initializing` state for an extended
```suggestion
    The cluster should typically be in the `Ready` state. It may briefly enter the `initializing` state while reconciling changes. If the cluster remains in the `initializing` state for an extended period, investigate further to identify any underlying issues.
```

2025-11-12 05:35 UTC, egegunes commented on docs/troubleshoot-operator.md
> +1. The Operator deployment must be in the `Running` state for the database cluster to function properly. Check the Operator Pod for restarts to identify potential issues.
```suggestion
1. The Operator pod must be in the `Running` state for the database cluster to function properly. Check the Operator Pod for restarts to identify potential issues.
```

2025-11-12 05:35 UTC, egegunes commented on docs/troubleshoot-operator.md
> +If multiple Kubernetes configurations are present in `kubeconfig`,check if you have set the correct context. If the context is wrong, switch it. Here's how:
```suggestion
If multiple Kubernetes configurations are present in `kubeconfig`, check if you have set the correct context. If the context is wrong, switch it. Here's how:
```

2025-11-13 13:53 UTC, nastena1606 commented
Waiting for the script to be in an official repo

2025-11-13 13:54 UTC, eleo007 requested changes

2025-11-13 13:54 UTC, eleo007 commented on docs/troubleshoot-operator.md
> +    bash <(curl -s https://gist.githubusercontent.com/cshiv/6048bdd0174275b48f633549c69d0844/raw/fd547b783a30b827362ee9f9ec03436f9bc79524/check_priviliges.sh)
Maybe this script should be moved to official percona repos instead of personal one?

2025-11-13 13:54 UTC, eleo007 commented on docs/troubleshoot-operator.md
> +3. Check the Operator logs
I would set checking logs as a first step TBH.

2025-11-13 13:54 UTC, eleo007 commented on docs/troubleshoot-operator.md
> +    kubectl get pg <database-cluster-name>
We can also add describe command for cluster

2025-11-13 13:54 UTC, eleo007 commented on docs/troubleshoot-operator.md
> +    kubectl logs <database-pod-name>
We can also add describe command

2025-11-13 14:04 UTC, nastena1606 commented on docs/troubleshoot-operator.md
> +    bash <(curl -s https://gist.githubusercontent.com/cshiv/6048bdd0174275b48f633549c69d0844/raw/fd547b783a30b827362ee9f9ec03436f9bc79524/check_priviliges.sh)
@hors WDYT?

2025-11-13 14:29 UTC, nastena1606 commented on docs/troubleshoot-operator.md
> +    kubectl logs <database-pod-name>
Added

2025-11-13 14:29 UTC, nastena1606 commented on docs/troubleshoot-operator.md
> +    kubectl get pg <database-cluster-name>
Added

2025-11-13 14:29 UTC, nastena1606 commented on docs/troubleshoot-operator.md
> +3. Check the Operator logs
Reordered

2025-11-13 14:36 UTC, eleo007 approved these changes

2025-11-13 14:41 UTC, merged