K8SPG-355 create cluster wide doc
percona/k8spg-docs pull request #59
Opened 2023-05-24 09:36 UTC by fiowro

2023-05-25 09:43 UTC, hors requested changes

2023-05-25 09:43 UTC, hors commented on docs/cluster-wide.md
> +        If you want to change the namespace, please edit
I discussed it with Ege yesterday, and Ege will improve it in the same way as we have for all other operators. Please wait for changes.

2023-05-25 09:43 UTC, hors commented on docs/cluster-wide.md
> +    $ kubectl config set-context $(kubectl config current-context) --namespace=percona-db-1
You should not do it you can just specify the namespace in line 154

2023-05-25 09:43 UTC, hors commented on docs/cluster-wide.md
> +    $ kubectl apply -f deploy/cr.yaml
```suggestion
    $ kubectl apply -f deploy/cr.yaml -n percona-db-1
```

2023-06-29 13:20 UTC, egegunes commented on docs/gke.md
> +    Operator and replica set Pods have reached their Running status:
```suggestion
    Operator and PostgreSQL Pods have reached their Running status:
```

2023-06-29 14:17 UTC, egegunes approved these changes

2023-06-29 14:23 UTC, hors approved these changes

2023-06-29 15:18 UTC, merged