Mention old docs archive in the upgrade doc, don't pause the operator latest versions
percona/k8spg-docs pull request #66
Opened 2023-06-02 11:55 UTC by fiowro

2023-06-02 16:51 UTC, hors requested changes
How to update DB:

remove 1 and 3 steps:
```
1 Pause the cluster in order to stop all possible activities:
3 Now you can enable the `pgbouncer` again:
```
and just use the following command to update cluster

`    $ kubectl patch perconapgcluster/<cluster-name> --type json -p '[{"op": "replace", "path": "/spec/backup/backrestRepoImage", "value": "percona/percona-postgresql-operator:{{ release }}-ppg14-pgbackrest-repo"},{"op":"replace","path":"/spec/backup/image","value":"percona/percona-postgresql-operator:{{ release }}-ppg13-pgbackrest"},{"op":"replace","path":"/spec/pgBadger/image","value":"percona/percona-postgresql-operator:{{ release }}-ppg14-pgbadger"},{"op":"replace","path":"/spec/pgBouncer/image","value":"percona/percona-postgresql-operator:{{ release }}-ppg14-pgbouncer"},{"op":"replace","path":"/spec/pgPrimary/image","value":"percona/percona-postgresql-operator:{{ release }}-ppg14-postgres-ha"},{"op":"replace","path":"/spec/userLabels/pgo-version","value":"v{{ release }}"},{"op":"replace","path":"/metadata/labels/pgo-version","value":"v{{ release }}"}]'`

and you can check that all deployment get new images 
`kubectl get deployment -o 'jsonpath={.spec.template.spec.containers[0].image}{"\n"}' --watch`

2023-06-02 16:51 UTC, hors commented on docs/update.md
> +1. Remove the old Operator version:
We should not remove old operator. We need to update the operator.
How to do it:
```
curl -s https://raw.githubusercontent.com/percona/percona-postgresql-operator/1.x/deploy/operator.yaml | yq w -d'4' -  "spec.template.spec.containers[0].env[0].value" "update" | kubectl apply -f -
kubectl wait --for=condition=Complete job/pgo-deploy --timeout=90s
```

2023-06-12 15:26 UTC, nmarukovich commented on docs/update.md
> +$ kubectl wait --for=condition=Complete job/pgo-deploy --timeout=90s
@fiowro did you test the commnad? I see at least problem with` | | `
and we have only one env here https://github.com/percona/percona-postgresql-operator/blob/1.x/deploy/operator.yaml#L173

2023-06-12 15:35 UTC, nmarukovich commented on docs/update.md
> +$ kubectl patch perconapgcluster/<cluster-name> --type json -p '[{"op": "replace", "path": "/spec/backup/backrestRepoImage", "value": "percona/percona-postgresql-operator:{{ release }}-ppg14-pgbackre
Why do we have 
`{"op":"replace","path":"/spec/backup/image","value":"percona/percona-postgresql-operator:{{ release }}-ppg13-pgbackrest"}`

2023-06-15 12:05 UTC, nmarukovich commented on docs/update.md
> +    a database management system. For PostgreSQL 13 you should change all
asumption  -> assumption

2023-06-15 12:18 UTC, nmarukovich approved these changes

2023-06-15 13:16 UTC, merged